#!/bin/bash

command="sleep 0.1; cat"

custom_options+=(--wait-on-stat)

function test_run()
{
	mkdir rootdir/dir
    local filename=dir/filename.1
	local translated_filename=dir/filename.2
    local file_contents="This is the first line.
This is the second line.
This is the third line."
    echo "$file_contents" >rootdir/$filename

    local expected_file_size=$(stat --format %s rootdir/$filename)
    read_file_size="$(stat --format %s mountpoint/$translated_filename)"
    assert [ "$expected_file_size" == "$read_file_size" ]
    assert_false lsof rootdir/$filename
}





