#!/bin/bash

executed_filename="$PWD/executed_num"
rm -f "$executed_filename"
command="bash -c '
echo line >>$executed_filename
number=\$(cat)
for ((i=0; i<number; ++i))
	do echo content
	sleep 0.01
done
'"

custom_options+=(--process-limit=1)

function test_run()
{
	local nowait_filename=nowait.1
	local nowait_translated_filename=nowait.2
	local wait_filename=wait.1
	local wait_translated_filename=wait.2
    echo 10 >rootdir/$nowait_filename
    echo 50 >rootdir/$wait_filename

	timeout 0.2 cat mountpoint/$wait_translated_filename >/dev/null &
	sleep 0.05
	timeout 0.1 cat mountpoint/$nowait_translated_filename >/dev/null &

	wait
	sleep 0.6
    local executed_count=$(cat "$executed_filename" | wc -l)
    assert [ 2 -eq $executed_count ]

	expected_file_contents=$(
		for ((i=0; i<10; ++i)); do
			echo content
		done
	)
	read_file_contents=$(cat mountpoint/$nowait_translated_filename)
	assert [ "$expected_file_contents" == "$read_file_contents" ]
    executed_count=$(cat "$executed_filename" | wc -l)
    assert [ 2 -eq $executed_count ]
}




